<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>WinExe</OutputType>

    <TargetFramework>net8.0-windows</TargetFramework>

    <UseWPF>true</UseWPF>

    <UseWindowsForms>true</UseWindowsForms>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>WinPadHost</AssemblyName>

    <RootNamespace>WinPadHost</RootNamespace>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
  </ItemGroup>

</Project>